### PR TITLE
format td judgements

### PR DESCRIPTION
**Pull request by incertia**
support %t in TD judgement section so we can avoid looping through 70-80 useless judgements (on average) per hit and simplify the TD judgement section. e.g.

```json
  "timeDependencyDecimalPrecision": 0,
  "timeDependencyDecimalOffset": 2,
  "timeDependencyJudgments": [
    {
      "threshold": 0.31,
      "text": "<color=#FF0000>%t</color>"
    },
    {
      "threshold": 0.21,
      "text": "<color=#FFFF00>%t</color>"
    },
    {
      "threshold": 0.11,
      "text": "<color=#00FF7F>%t</color>"
    },
    {
      "threshold": 0.06,
      "text": "<color=#2D9DAD>%t</color>"
    },
    {
      "threshold": 0,
      "text": "<color=#FFFFFF>%t</color>"
    }
```

maybe also consider doing TD from bottom up instead of top down since lower is better tm.

### CODE REVIEW

**Comment by ErisApps** [comment]
Just noticed that you had created this PR. I'll try to check it fully sometime this weekend when all mods are fully updated again.

As for your suggestion to change the order, that would be a breaking change technically so I rather not right now.
That being said, I'll keep it in mind when bigger changes are required in that part of the config 😸 

Anyways, thanks a lot for the contribution.

**Comment by incertia** [comment]
merged `master` back into this branch

**Comment by incertia** [comment]
any updates on this?

**Comment by ErisApps** [comment]
Sorry, had a lot of things going on so haven't had the time just yet to check it out.
I'll try to give this PR a look before I release a new version for 1.17.0

**Comment by ErisApps** [comment]
New version will be released one of the upcoming days, has to go through some more testing first as quite a few things have changed.

**Pull request merged**
